name: Build (wheel + sdist)

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - "src/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/build.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv (official)
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version

      - name: Cache uv and venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-build-${{ runner.os }}-3.11-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Create venv & sync (prod only)
        run: |
          uv sync --frozen

      - name: Build (hatchling via uv)
        run: |
          uv build
          ls -l dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
          if-no-files-found: error
